package edu.pe.unsch.entities;
// Generated 8/06/2019 07:46:25 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria", catalog = "electro")
public class Categoria implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Boolean estado;
	private Integer idPadre;
	private Set<Producto> productos = new HashSet<Producto>(0);
	private List<Categoria> categories;

	public Categoria() {
	}

	public Categoria(String nombre, Boolean estado, Integer idPadre, Set<Producto> productos) {
		this.nombre = nombre;
		this.estado = estado;
		this.idPadre = idPadre;
		this.productos = productos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Column(name = "id_padre")
	public Integer getIdPadre() {
		return this.idPadre;
	}

	public void setIdPadre(Integer idPadre) {
		this.idPadre = idPadre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}
	
	@OneToMany
	@JoinColumn(name = "id_padre", referencedColumnName = "id")
	public List<Categoria> getCategories() {
		return categories;
	}
	
	public void setCategories(List<Categoria> categories) {
		this.categories = categories;
	}

}
