package edu.pe.unsch.entities;
// Generated 1/06/2019 07:38:06 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set productos = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String nombre, Set productos) {
		this.nombre = nombre;
		this.productos = productos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getProductos() {
		return this.productos;
	}

	public void setProductos(Set productos) {
		this.productos = productos;
	}

}
