package edu.pe.unsch.entities;
// Generated 1/06/2019 07:38:06 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private String telefono;
	private String direccion;
	private Set compras = new HashSet(0);

	public Cliente() {
	}

	public Cliente(Usuario usuario, String telefono, String direccion, Set compras) {
		this.usuario = usuario;
		this.telefono = telefono;
		this.direccion = direccion;
		this.compras = compras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getCompras() {
		return this.compras;
	}

	public void setCompras(Set compras) {
		this.compras = compras;
	}

}
