package edu.pe.unsch.entities;
// Generated 1/06/2019 07:38:06 PM by Hibernate Tools 5.4.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private Cupon cupon;
	private Estadoproductocompra estadoproductocompra;
	private Metodopago metodopago;
	private Date creacion;
	private Set detallecompras = new HashSet(0);

	public Compra() {
	}

	public Compra(Cliente cliente, Cupon cupon, Estadoproductocompra estadoproductocompra, Metodopago metodopago,
			Date creacion, Set detallecompras) {
		this.cliente = cliente;
		this.cupon = cupon;
		this.estadoproductocompra = estadoproductocompra;
		this.metodopago = metodopago;
		this.creacion = creacion;
		this.detallecompras = detallecompras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Cupon getCupon() {
		return this.cupon;
	}

	public void setCupon(Cupon cupon) {
		this.cupon = cupon;
	}

	public Estadoproductocompra getEstadoproductocompra() {
		return this.estadoproductocompra;
	}

	public void setEstadoproductocompra(Estadoproductocompra estadoproductocompra) {
		this.estadoproductocompra = estadoproductocompra;
	}

	public Metodopago getMetodopago() {
		return this.metodopago;
	}

	public void setMetodopago(Metodopago metodopago) {
		this.metodopago = metodopago;
	}

	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	public Set getDetallecompras() {
		return this.detallecompras;
	}

	public void setDetallecompras(Set detallecompras) {
		this.detallecompras = detallecompras;
	}

}
