package edu.pe.unsch.entities;
// Generated 25/06/2019 10:17:00 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "compra", catalog = "electro")
public class Compra implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private Cupon cupon;
	private Estadoproductocompra estadoproductocompra;
	private Metodopago metodopago;
	private Date creacion;
	private Set<Detallecompra> detallecompras = new HashSet<Detallecompra>(0);

	public Compra() {
	}

	public Compra(Cliente cliente, Cupon cupon, Estadoproductocompra estadoproductocompra, Metodopago metodopago,
			Date creacion, Set<Detallecompra> detallecompras) {
		this.cliente = cliente;
		this.cupon = cupon;
		this.estadoproductocompra = estadoproductocompra;
		this.metodopago = metodopago;
		this.creacion = creacion;
		this.detallecompras = detallecompras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cupon")
	public Cupon getCupon() {
		return this.cupon;
	}

	public void setCupon(Cupon cupon) {
		this.cupon = cupon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_estado_producto_compra")
	public Estadoproductocompra getEstadoproductocompra() {
		return this.estadoproductocompra;
	}

	public void setEstadoproductocompra(Estadoproductocompra estadoproductocompra) {
		this.estadoproductocompra = estadoproductocompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_metodo_pago")
	public Metodopago getMetodopago() {
		return this.metodopago;
	}

	public void setMetodopago(Metodopago metodopago) {
		this.metodopago = metodopago;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion", length = 19)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compra")
	public Set<Detallecompra> getDetallecompras() {
		return this.detallecompras;
	}

	public void setDetallecompras(Set<Detallecompra> detallecompras) {
		this.detallecompras = detallecompras;
	}

}
