package edu.pe.unsch.entities;
// Generated 22/07/2019 11:51:13 PM by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cupon generated by hbm2java
 */
@Entity
@Table(name = "cupon", catalog = "electro")
public class Cupon implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String descripcion;
	private Integer idProducto;
	private Double valor;
	private Integer tipo;
	private Boolean estado;
	private Date TComienzo;
	private Date TFinal;
	private Date creacion;

	public Cupon() {
	}

	public Cupon(String nombre, String descripcion, Integer idProducto, Double valor, Integer tipo, Boolean estado,
			Date TComienzo, Date TFinal, Date creacion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.idProducto = idProducto;
		this.valor = valor;
		this.tipo = tipo;
		this.estado = estado;
		this.TComienzo = TComienzo;
		this.TFinal = TFinal;
		this.creacion = creacion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 200)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 1000)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "id_producto")
	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	@Column(name = "valor", precision = 22, scale = 0)
	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	@Column(name = "tipo")
	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "t_comienzo", length = 10)
	public Date getTComienzo() {
		return this.TComienzo;
	}

	public void setTComienzo(Date TComienzo) {
		this.TComienzo = TComienzo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "t_final", length = 10)
	public Date getTFinal() {
		return this.TFinal;
	}

	public void setTFinal(Date TFinal) {
		this.TFinal = TFinal;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creacion", length = 19)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

}
