package edu.pe.unsch.entities;
// Generated 1/06/2019 07:38:06 PM by Hibernate Tools 5.4.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cupon generated by hbm2java
 */
public class Cupon implements java.io.Serializable {

	private Integer id;
	private Producto producto;
	private String nombre;
	private String descripcion;
	private Double valor;
	private Integer tipo;
	private Boolean estado;
	private Date tcomienzo;
	private Date tfinal;
	private Date creacion;
	private Set compras = new HashSet(0);

	public Cupon() {
	}

	public Cupon(Producto producto, String nombre, String descripcion, Double valor, Integer tipo, Boolean estado,
			Date tcomienzo, Date tfinal, Date creacion, Set compras) {
		this.producto = producto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.valor = valor;
		this.tipo = tipo;
		this.estado = estado;
		this.tcomienzo = tcomienzo;
		this.tfinal = tfinal;
		this.creacion = creacion;
		this.compras = compras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getValor() {
		return this.valor;
	}

	public void setValor(Double valor) {
		this.valor = valor;
	}

	public Integer getTipo() {
		return this.tipo;
	}

	public void setTipo(Integer tipo) {
		this.tipo = tipo;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Date getTcomienzo() {
		return this.tcomienzo;
	}

	public void setTcomienzo(Date tcomienzo) {
		this.tcomienzo = tcomienzo;
	}

	public Date getTfinal() {
		return this.tfinal;
	}

	public void setTfinal(Date tfinal) {
		this.tfinal = tfinal;
	}

	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	public Set getCompras() {
		return this.compras;
	}

	public void setCompras(Set compras) {
		this.compras = compras;
	}

}
