package edu.pe.unsch.entities;
// Generated 1/06/2019 07:38:06 PM by Hibernate Tools 5.4.2.Final

/**
 * Detallecompra generated by hbm2java
 */
public class Detallecompra implements java.io.Serializable {

	private Integer id;
	private Compra compra;
	private Producto producto;
	private Integer cantidad;

	public Detallecompra() {
	}

	public Detallecompra(Compra compra, Producto producto, Integer cantidad) {
		this.compra = compra;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
