package edu.pe.unsch.entities;
// Generated 1/06/2019 07:38:06 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Estadoproductocompra generated by hbm2java
 */
public class Estadoproductocompra implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Set compras = new HashSet(0);

	public Estadoproductocompra() {
	}

	public Estadoproductocompra(String nombre, Set compras) {
		this.nombre = nombre;
		this.compras = compras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCompras() {
		return this.compras;
	}

	public void setCompras(Set compras) {
		this.compras = compras;
	}

}
