package edu.pe.unsch.entities;
// Generated 1/06/2019 07:38:06 PM by Hibernate Tools 5.4.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Metodopago generated by hbm2java
 */
public class Metodopago implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Boolean estado;
	private Set compras = new HashSet(0);

	public Metodopago() {
	}

	public Metodopago(String nombre, Boolean estado, Set compras) {
		this.nombre = nombre;
		this.estado = estado;
		this.compras = compras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	public Set getCompras() {
		return this.compras;
	}

	public void setCompras(Set compras) {
		this.compras = compras;
	}

}
