package edu.pe.unsch.entities;
// Generated 1/06/2019 07:38:06 PM by Hibernate Tools 5.4.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer id;
	private Categoria categoria;
	private String nombre;
	private String codigo;
	private String descripcion;
	private String textoOferta;
	private String imagen;
	private Boolean destacado;
	private Boolean publico;
	private Boolean existencia;
	private Date creacion;
	private Date ordenado;
	private Float precio;
	private Set detallecompras = new HashSet(0);
	private Set cupons = new HashSet(0);

	public Producto() {
	}

	public Producto(Categoria categoria, String nombre, String codigo, String descripcion, String textoOferta,
			String imagen, Boolean destacado, Boolean publico, Boolean existencia, Date creacion, Date ordenado,
			Float precio, Set detallecompras, Set cupons) {
		this.categoria = categoria;
		this.nombre = nombre;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.textoOferta = textoOferta;
		this.imagen = imagen;
		this.destacado = destacado;
		this.publico = publico;
		this.existencia = existencia;
		this.creacion = creacion;
		this.ordenado = ordenado;
		this.precio = precio;
		this.detallecompras = detallecompras;
		this.cupons = cupons;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTextoOferta() {
		return this.textoOferta;
	}

	public void setTextoOferta(String textoOferta) {
		this.textoOferta = textoOferta;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Boolean getDestacado() {
		return this.destacado;
	}

	public void setDestacado(Boolean destacado) {
		this.destacado = destacado;
	}

	public Boolean getPublico() {
		return this.publico;
	}

	public void setPublico(Boolean publico) {
		this.publico = publico;
	}

	public Boolean getExistencia() {
		return this.existencia;
	}

	public void setExistencia(Boolean existencia) {
		this.existencia = existencia;
	}

	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

	public Date getOrdenado() {
		return this.ordenado;
	}

	public void setOrdenado(Date ordenado) {
		this.ordenado = ordenado;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public Set getDetallecompras() {
		return this.detallecompras;
	}

	public void setDetallecompras(Set detallecompras) {
		this.detallecompras = detallecompras;
	}

	public Set getCupons() {
		return this.cupons;
	}

	public void setCupons(Set cupons) {
		this.cupons = cupons;
	}

}
